namespace BengalTex.ERP.Application.GatePasses.Dtos;

public sealed record GatePassDto(
    long Id,
    string Code,
    DateOnly PassDate,
    TimeOnly? PassTime,
    string Type,
    string Direction,
    string? VehicleNumber,
    string? DriverName,
    string? DriverPhone,
    string? DriverNidNumber,
    string? TransporterName,
    string? VisitorName,
    string? VisitorPhone,
    string? VisitorOrganization,
    string? VisitorPurpose,
    string? ItemDescription,
    string? Quantity,
    string? FromLocation,
    string? ToLocation,
    string? SourceType,
    long? SourceId,
    string? SourceCode,
    string? IssuedByUser,
    string? ApprovedByUser,
    DateOnly? ExpectedReturnDate,
    DateTimeOffset? ReturnedAt,
    string? ReturnedByUser,
    string? ReturnNotes,
    DateTimeOffset? ClosedAt,
    string Status,
    bool IsOverdue,           // computed: ReturnableOut + today > ExpectedReturnDate + not yet returned
    string? Notes);
